### ISSUE TITLE
Include k8s manifest file

### ISSUE THREAD

**Issue by onedr0p** [stefancrain/folding-at-home#2]
You want want to put this in the repo, I don't know if I will be running it for awhile because not having GPU really limits my WUs

```yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: folding-at-home
  labels:
    app: folding-at-home
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: folding-at-home
  template:
    metadata:
      labels:
        app: folding-at-home
    spec:
      containers:
        - name: folding-at-home
          image: stefancrain/folding-at-home:7.5.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/tini", "--", "/usr/bin/FAHClient", "--web-allow=0/0:7396", "--allow=0/0:7396", "--smp=true"]
          args: ["--user=Devin_Buhl", "--team=241985", "--gpu=false", "--power=full"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values: 
                  - "true"
---
apiVersion: v1
kind: Service
metadata:
  name: folding-at-home
spec:
  selector:
    app: folding-at-home
  type: NodePort
  ports:
    - port: 7396
      nodePort: 30160
      targetPort: 7396
```
